### ISSUE TITLE
Death Minigames

### ISSUE THREAD

**Issue by PrinzPizza42** [AtomPilz-DevTeam/StationofDoomPlugin#134]
On death the items get saved and the player who lost them can get them back by doing one of various, random or not?, minigames. One option could also be just getting them dropped on the place the player died with a command, if the player for example respawned near the place he died, so doesnt have to do the minigame and can get them back the normal way. This should change it, so the player is not as annoyed to lose all his items, but has a chance to get them back with a bit of skill.

Maybe there could be an introduction with a bit of story of a god giving the player the chance the first time he is dying. After that, it would be just the minigame.

The minigame could have various forms, i imagine maybe a jump and run or a fight with a given equipment but it could also be a minigame inside a chest inventory.

Instead of the commands a possibility could also be put the player after he respawns before the decision which one of the two options he wants to do, to not confuse people where their loot is, who dont know about the plugin. This should be done with a timer, to not let the player save his whole inventory, by just getting to his death point and then letting his stuff drop

**Comment by JonasFranke** [comment]
Great idea! Would love to see that.

**Comment by PrinzPizza42** [comment]
from Niko: maybe use the key that is planned to drop to the player when completing the minigame, to open a room, in which the items could be. Some special items could also be displayed on armorstands. It could be possible to do that by listing every piece of armor in an array or something like that and check the saved inventory of the player after his death for them. For the possibility of several armor pieces that are put in the same spot, like 2 helmets, there could be placed more armorstands.

**Comment by PrinzPizza42** [comment]
We already have a PR for this, therefore im closing this issue.
