### ISSUE TITLE
Website with important details of the server

### ISSUE THREAD

**Issue by PrinzPizza42** [AtomPilz-DevTeam/StationofDoomPlugin#135]
with a link the player can get to a website which displays the map of the server, maybe just the default map generated by the seed of the world without any changes from the players. On this website there can also be infos displayed like active players and maybe stats of the players, or who already has played on the server at all.

the player could type "/website" in the chat to get the link to the website.

complicated Features for the future:
- almost live map (maybe registers changes every 2 hours or so to not lower the performance of the server)
- live location of the players (maybe every few ticks or somethign like that for the same reason)
- more features to display
- maybe even interactive things, that can also change things ingame, like a team system, which will be displayed while pressing tab ingame. These things could also be changed on the website for an easier user experience

**Comment by JonasFranke** [comment]
- [ ] Basic website setup
- [ ] Team system

**Comment by MisterDoenerHD** [comment]
The website could have an account system, that you link to your Minecraft Account using a chat message authentification. 
This could allow you to open / join / leave teams, make Admin actions from the website (ban/kick a player) or maybe even access the servers console. 
Another use of this feature could be viewing your ingame stats.
